### ISSUE TITLE
Published version

### ISSUE THREAD

**Issue by mywill** [ebts/jet#6]
I'm looking to use this in a project and couldn't find it in a public repo.
Is this published to maven central or any public place?
If not would it be possible start publishing versions?

**Comment by adamday2** [comment]
It isn't pushed to Maven, but definitely should be. I'll work on that this week.

**Comment by adamday2** [comment]
Requested and received account to push to Sonatype. Will be working on first maven release shortly.

**Comment by mywill** [comment]
@adamday2 Awesome!  Thank You

**Comment by adamday2** [comment]
@jej2003

https://oss.sonatype.org/content/repositories/snapshots/org/mitre/jet/jet/1.0-SNAPSHOT/

**Comment by jej2003** [comment]
@adamday2, I'll have the team verify the change today.  Once we've had a chance to do so either I or @mywill will let you know so that you can publish a final version.  Thanks again!

**Comment by mywill** [comment]
@adamday2 When i try and run the published jar i get a java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer; error when parsing the efts.  If i build and publish Jet locally it seems to work as expected.

**Comment by adamday2** [comment]
@mywill google seems to point to it being a Java 8 vs. Java 9+ issue. I'll strip out the 1.8 version  from the pom and repush it again this evening.

**Comment by jej2003** [comment]
Agree on the issue, but I am not sure that stripping out the version 1.8 tags will help us as we are still running Java 1.8.  I suppose the question is what version of Java are you expecting people to have to run to use the library?  I am not intimately familiar with this specific issue but others that have run into it seem to indicate that this is an issue when building on Java 9 and targeting Java 8.  

A similar issue is shown [here](https://github.com/eclipse/jetty.project/issues/3244#issuecomment-452378420).  

Ideally in our case this would be built using Java 1.8 targeting 1.8, which should make it possible to run on both Java 1.8 and 1.9.  Thoughts?

**Comment by adamday2** [comment]
Given the user-base, keeping at 1.8 is probably preferred. 
I'll recompile with 1.8 and see where that puts us. I'll update the ticket when the new version lands.

**Comment by adamday2** [comment]
Just pushed an update to the snapshot

Apparently
`release` replaced `source` and `target` and *should* solve the issue.

**Comment by mywill** [comment]
@adamday2 The new snapshot works for us. Will you be making a final version?

**Comment by adamday2** [comment]
Great! I'll push a 1.0.0 out this evening.

**Comment by adamday2** [comment]
@mywill 1.0.0 pushed

Thanks for your help supporting JET!

**Comment by mywill** [comment]
@adamday2 Thanks for all the assistance

**Comment by jej2003** [comment]
@adamday2, was a 1.0.0 ever published?  I see it in git but don't see it in the nexus repo at https://oss.sonatype.org/#nexus-search;gav~org.mitre.jet~jet~~~ only the snapshot

**Comment by adamday2** [comment]
@jej2003 it should be up there. oss.sonatype.org seems to be having some issues at the moment, but I'll check periodically and get it up if something went wrong with my deployment

**Comment by adamday2** [comment]
Apparently there is a lot more to required pushing a release than a snapshot. I didn't realize my push was only going to staging environment. I'll have to make some changes to get it up and running.

**Comment by jej2003** [comment]
Hey @adamday2 , any updates on this?

**Comment by jej2003** [comment]
Just checking in on if there has been any status updates on this?

**Comment by esamini** [comment]
Hi.

It seems the Maven repository has issues. Any alternative is available?

**Comment by adamday2** [comment]
No updates. I haven't had an opportunity to go through the sonatype publish process. The snapshot should be available here:

https://oss.sonatype.org/content/repositories/snapshots/org/mitre/jet/jet/1.0-SNAPSHOT/
